-- MySQL Script generated by MySQL Workbench
-- Mon Apr 23 17:15:38 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema html
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema html
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `html` DEFAULT CHARACTER SET utf8 ;
USE `html` ;

-- -----------------------------------------------------
-- Table `html`.`dataform`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `html`.`dataform` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `form1_fullname` VARCHAR(50) NULL DEFAULT NULL,
  `form2_sex` VARCHAR(50) NULL DEFAULT NULL,
  `form3_birthday` DATE NULL DEFAULT NULL,
  `form4_place_of_birth` VARCHAR(50) NULL DEFAULT NULL,
  `form5_nationality_at_birth` VARCHAR(50) NULL DEFAULT NULL,
  `form6_current_nationality` VARCHAR(50) NULL DEFAULT NULL,
  `form7_religion` VARCHAR(50) NULL DEFAULT NULL,
  `form8_occupation` VARCHAR(50) NULL DEFAULT NULL,
  `form9_buiness_address` VARCHAR(50) NULL DEFAULT NULL,
  `form10_permanent_residential_address` VARCHAR(50) NULL DEFAULT NULL,
  `form10_tel_email` VARCHAR(50) NULL DEFAULT NULL,
  `form11_family_members` VARCHAR(1200) NULL DEFAULT NULL,
  `form12_passport` VARCHAR(50) NULL DEFAULT NULL,
  `form12_type` VARCHAR(50) NULL DEFAULT NULL,
  `form12_issuing_authority` VARCHAR(50) NULL DEFAULT NULL,
  `form12_day` DATE NULL DEFAULT NULL,
  `form13_day` DATE NULL DEFAULT NULL,
  `form14_day` DATE NULL DEFAULT NULL,
  `form14_stayday` VARCHAR(50) NULL DEFAULT NULL,
  `form15_purpose_of_entry` VARCHAR(50) NULL DEFAULT NULL,
  `form16_address` VARCHAR(50) NULL DEFAULT NULL,
  `form17_organisation` VARCHAR(50) NULL DEFAULT NULL,
  `form17_address1` VARCHAR(50) NULL DEFAULT NULL,
  `form17_fullname` VARCHAR(50) NULL DEFAULT NULL,
  `form17_address2` VARCHAR(50) NULL DEFAULT NULL,
  `form17_relationship` VARCHAR(50) NULL DEFAULT NULL,
  `form18_accompanying_children` VARCHAR(300) NULL DEFAULT NULL,
  `form19_applying_visa` VARCHAR(50) NULL DEFAULT NULL,
  `form19_startday` DATE NULL DEFAULT NULL,
  `form19_endday` DATE NULL DEFAULT NULL,
  `form20_other_requests` VARCHAR(50) NULL DEFAULT NULL,
  `form20_at` VARCHAR(50) NULL DEFAULT NULL,
  `form21_day` DATE NULL DEFAULT NULL,
  `image` VARCHAR(500) NULL DEFAULT NULL,
  `created_at` BIGINT(20) NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
