-- MySQL Script generated by MySQL Workbench
-- Wed Apr 18 15:24:00 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`table1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`table1` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`MainForm`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`MainForm` (
  `id` INT unsigned auto_increment NOT NULL,
  `form1_fullname` VARCHAR(45) NULL,
  `form12_Passport` VARCHAR(45) NOT NULL,
  `form2_sex` VARCHAR(5) NULL,
  `form3_birthday` DATE NULL,
  `form4_Place_of_birth` VARCHAR(45) NULL,
  `form5_Nationality_at_birth` VARCHAR(45) NULL,
  `form6_Current_nationality` VARCHAR(45) NULL,
  `form7_Religion` VARCHAR(45) NULL,
  `form8_Occupation` VARCHAR(45) NULL,
  `form9_Buiness_address` VARCHAR(45) NULL,
  `form10_Permanent_residential_address` VARCHAR(45) NULL,
  `form10_Tel_Email` VARCHAR(45) NULL,
  `form12_Type` VARCHAR(45) NULL,
  `form12_Issuing_authority` VARCHAR(45) NULL,
  `form12_day` DATE NULL,
  `form13_day` DATE NULL,
  `form14_day` DATE NULL,
  `form14_stayday` INT NULL,
  `form15_Purpose_of_entry` VARCHAR(45) NULL,
  `form16_address` VARCHAR(45) NULL,
  `form17_organisation` VARCHAR(45) NULL,
  `form17_address1` VARCHAR(45) NULL,
  `form17_fullname` VARCHAR(45) NULL,
  `form17_address2` VARCHAR(45) NULL,
  `form17_relationship` VARCHAR(45) NULL,
  `form19` VARCHAR(45) NULL,
  `form19_day1` DATE NULL,
  `form19_day2` DATE NULL,
  `form20_Other_requests` VARCHAR(45) NULL,
  `form20_at` VARCHAR(45) NULL,
  `form21_day` DATE NULL,
  PRIMARY KEY (`form12_Passport`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Form11`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Form11` (
  `table2_form12_Passport` VARCHAR(45) NOT NULL,
  `id` INT unsigned auto_increment NOT NULL,
  `form11_Relationship` VARCHAR(45) NULL,
  `form11_Fullname` VARCHAR(100) NULL,
  `form11_Sex` VARCHAR(45) NULL,
  `form11_BirthDay` VARCHAR(100) NULL,
  `form11_Nationality` VARCHAR(100) NULL,
  `form11_Permanent_residential_address` VARCHAR(100) NULL,
  INDEX `fk_table3_table2_idx` (`table2_form12_Passport` ASC),
  CONSTRAINT `fk_table3_table2`
    FOREIGN KEY (`table2_form12_Passport`)
    REFERENCES `mydb`.`MainForm` (`form12_Passport`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Form18`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Form18` (
  `table2_form12_Passport` VARCHAR(45) NOT NULL,
  `form18_id` INT unsigned auto_increment NOT NULL,
  `form18_fullname` VARCHAR(100) NULL,
  `form18_sex` VARCHAR(20) NULL,
  `form18_birthday` VARCHAR(50) NULL,
  INDEX `fk_table4_table21_idx` (`table2_form12_Passport` ASC),
  CONSTRAINT `fk_table4_table21`
    FOREIGN KEY (`table2_form12_Passport`)
    REFERENCES `mydb`.`MainForm` (`form12_Passport`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`FormImage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`FormImage` (
  `id` INT  unsigned auto_increment NOT NULL,
  `MainForm_form12_Passport` VARCHAR(45) NOT NULL,
  `profile` VARCHAR(45) NOT NULL,
  INDEX `fk_FormImage_MainForm1_idx` (`MainForm_form12_Passport` ASC),
  CONSTRAINT `fk_FormImage_MainForm1`
    FOREIGN KEY (`MainForm_form12_Passport`)
    REFERENCES `mydb`.`MainForm` (`form12_Passport`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
